Update env.yml

diff --git a/.github/workflows/env.yml b/.github/workflows/env.yml
--- a/.github/workflows/env.yml
+++ b/.github/workflows/env.yml
@@ -1,36 +1,50 @@
-name: Environment Pipeline Trigger
+name: pull request comment
 
-# on:
-#   issues:
-#     types:
-#       - closed
-#   push:
-#   workflow_dispatch:
-    # inputs:
-    #   environment:
-    #     description: 'Environment to Deploy on'
-    #     required: true
-    #     type: environment
-  
+on:
+  issue_comment:                                     
+    types: [created, edited, deleted]
 
 jobs:
-  trigger_pipeline:
+   run_pipeline:
+    if: contains(github.event.issue.html_url, '/issues/')  # Check if the comment is associated with an issue
     runs-on: ubuntu-latest
 
     steps:
-      - name: Check if issue is closed
-        id: check_issue
-        run: echo "IS_ISSUE_CLOSED=${{ github.event_name == 'issues' && github.event.action == 'closed' }}" >> $GITHUB_ENV
-
-      - name: Check environment label
-        id: check_environment
-        if: env.IS_ISSUE_CLOSED == 'true'
-        run: echo "ENVIRONMENT=${{ join(github.event.issue.labels.*.name, ',') }}" >> $GITHUB_ENV
-
-      - name: Trigger pipeline for Stage
-        if: env.IS_ISSUE_CLOSED == 'true' && env.ENVIRONMENT == 'stage'
+      - name: Check if the comment is on a closed issue
+        env:
+          VARS_CONTEXT: ${{ toJson(vars) }}
+          GITHUB_CONTEXT: ${{ toJson(github) }}
         run: |
-          # Your pipeline trigger code for the 'stage' environment goes here
-          echo "Pipeline for Stage Environment triggered."
+          ls $(pwd)
+          echo "$GITHUB_CONTEXT"
+          comment_body=$(jq -r .comment.body "${{ github.event_path }}")
+          echo $comment_body
+          if [ "${{ github.event_name }}" == "issue_comment" ] && [ "${{ github.event.action }}" == "created" -o "${{ github.event.action }}" == "edited" ]; then
+            echo "Checking comment for approval or denial..."
+          else
+            echo "Not a relevant event. Exiting..."
+            exit 0
+          fi
+      - name: Check comment for approval or denial
+        run: |
+          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
+          last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
+          echo "Last Comment Body: $last_comment_body"
+          
+          if [[ $last_comment_body == *'/approve'* ]]; then
+            echo "Comment contains '/approve'. Pipeline will run successfully."
+          elif [[ $last_comment_body == *'/deny'* ]]; then
+            echo "Comment contains '/deny'. Pipeline will fail."
+            exit 1
+          else
+            echo "No '/approve' or '/deny' keyword found. Exiting..."
+            exit 0
+          fi
 
-      # Add similar steps for other environments (dev, qa) as needed
+      - name: say hello
+        run: |
+          echo say hello
+
+      - name: test
+        run: |
+          echo test
