Update env.yml

diff --git a/.github/workflows/env.yml b/.github/workflows/env.yml
--- a/.github/workflows/env.yml
+++ b/.github/workflows/env.yml
@@ -31,24 +31,24 @@ jobs:
           last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
           echo "Last Comment Body: $last_comment_body"
           
-          if [[ $last_comment_body == *'/approve'* ]]; then
-            echo "Comment contains '/approve'. Pipeline will run successfully."
-          elif [[ $last_comment_body == *'/deny'* ]]; then
-            echo "Comment contains '/deny'. Pipeline will fail."
-            exit 1
-          else
-            echo "No '/approve' or '/deny' keyword found. Exiting..."
-            exit 0
-          fi
+          # if [[ $last_comment_body == *'/approve'* ]]; then
+          #   echo "Comment contains '/approve'. Pipeline will run successfully."
+          # elif [[ $last_comment_body == *'/deny'* ]]; then
+          #   echo "Comment contains '/deny'. Pipeline will fail."
+          #   exit 1
+          # else
+          #   echo "No '/approve' or '/deny' keyword found. Exiting..."
+          #   exit 0
+          # fi
 
       - name: say hello
-        if: contains(github.event.comment.body, '/support')   # check the comment if it contains the keywords
+        if: contains(github.event.comment.body, '/approve')   # check the comment if it contains the keywords
         run: |
-          echo say hello
+          echo approve
       - name: test
-        if: contains(github.event.comment.body, '/test')  # check the comment if it contains the keywords
+        if: contains(github.event.comment.body, '/deny')  # check the comment if it contains the keywords
         run: |
-         echo test
+           exit 1
 
       - name: Checkout code
         uses: actions/checkout@v2
