Update issue-approval.yml

diff --git a/.github/workflows/issue-approval.yml b/.github/workflows/issue-approval.yml
--- a/.github/workflows/issue-approval.yml
+++ b/.github/workflows/issue-approval.yml
@@ -24,23 +24,27 @@ jobs:
             echo "Not a relevant event. Exiting..."
             exit 0
           fi
-      - name: Check comment for approval or denial
-        run: |
-          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
-          last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
-          echo "Last Comment Body: $last_comment_body"
+
+      - name: check comment
+        if: contains(github.event.comment.body, '/approve')
+     
+      # - name: Check comment for approval or denial
+      #   run: |
+      #     comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
+      #     last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
+      #     echo "Last Comment Body: $last_comment_body"
           
         
-          if [[ "$last_comment_body" == *"approve"* ]]; then
-            echo "Pipeline approved. Running the pipeline..."
-            # Add your pipeline execution command here
-          elif [[ "$last_comment_body" == *"deny"* ]]; then
-            echo "Pipeline denied. Failing the pipeline."
-            exit 1
-          else
-            echo "No action required for this comment."
-            exit 0
-          fi
+      #     if [[ "$last_comment_body" == *"approve"* ]]; then
+      #       echo "Pipeline approved. Running the pipeline..."
+      #       # Add your pipeline execution command here
+      #     elif [[ "$last_comment_body" == *"deny"* ]]; then
+      #       echo "Pipeline denied. Failing the pipeline."
+      #       exit 1
+      #     else
+      #       echo "No action required for this comment."
+      #       exit 0
+      #     fi
       # - name: Run Pipeline
       #   if: success()  # Only run if the comment was processed successfully
       #   run: |
