Update issue-approval.yml

diff --git a/.github/workflows/issue-approval.yml b/.github/workflows/issue-approval.yml
--- a/.github/workflows/issue-approval.yml
+++ b/.github/workflows/issue-approval.yml
@@ -1,9 +1,9 @@
 name: Issue approval Pipeline
 
-# on:
-#   issues:
-#     types:
-#       - closed    
+on:
+  issues:
+    types:
+      - closed    
      
 
 jobs:
@@ -24,35 +24,34 @@ jobs:
             echo "Issue is closed. Checking comment for approval or denial..."
           else
             echo "Not a relevant event. Exiting..."
-            exit 0
+            exit 1
           fi
 
       - name: Check comment for approval or denial
         run: |
           comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
           last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
-          echo "Last Comment Body: $last_comment_body"
-          
+          echo "Last Comment Body: $last_comment_body"          
         
-          if [[ "$last_comment_body" == *"approve"* ]]; then
+          if [[ "$last_comment_body" == "approve" ]]; then
             echo "Pipeline approved. Running the pipeline..."
-            # Add your pipeline execution command here
-          elif [[ "$last_comment_body" == *"deny"* ]]; then
+          elif [[ "$last_comment_body" == "deny" ]]; then
             echo "Pipeline denied. Failing the pipeline."
             exit 1
           else
-            echo "No action required for this comment."
-            exit 0
+            echo "Action not identified. Pipeline denied. Failing the pipeline."
+            exit 1
           fi
       # - name: Run Pipeline
       #   if: success()  # Only run if the comment was processed successfully
       #   run: |
       #     # Your pipeline steps go here
+      
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v3
-        with:
-         node-version: 14 
+      # - name: Set up Node.js
+      #   uses: actions/setup-node@v3
+      #   with:
+      #    node-version: 14 
         
