Update private approval.yml

diff --git a/.github/workflows/private approval.yml b/.github/workflows/private approval.yml
--- a/.github/workflows/private approval.yml
+++ b/.github/workflows/private approval.yml
@@ -33,21 +33,21 @@ jobs:
             exit 1
           fi
 
-      - name: Check comment for approval or denial
-        run: |
-          comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
-          last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
-          echo "Last Comment Body: $last_comment_body"          
+      # - name: Check comment for approval or denial
+      #   run: |
+      #     comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
+      #     last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
+      #     echo "Last Comment Body: $last_comment_body"          
         
-          if [[ "$last_comment_body" == "approve" ]]; then
-            echo "Pipeline approved. Running the pipeline..."
-          elif [[ "$last_comment_body" == "deny" ]]; then
-            echo "Pipeline denied. Failing the pipeline."
-            exit 1
-          else
-            echo "Action not identified. Pipeline denied. Failing the pipeline."
-            exit 1
-          fi
+      #     if [[ "$last_comment_body" == "approve" ]]; then
+      #       echo "Pipeline approved. Running the pipeline..."
+      #     elif [[ "$last_comment_body" == "deny" ]]; then
+      #       echo "Pipeline denied. Failing the pipeline."
+      #       exit 1
+      #     else
+      #       echo "Action not identified. Pipeline denied. Failing the pipeline."
+      #       exit 1
+      #     fi
 
       - name: Check comment for approval or denial
         run: |
