Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,4 +1,4 @@
-name: Issue approval Pipeline
+name: test approval
 
 on:
   issues:
@@ -29,18 +29,18 @@ jobs:
           comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
           last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
           echo "Last Comment Body: $last_comment_body"
-    
-          if [ "$last_comment_body" == "approve" ]; then
-          echo "Pipeline approved. Running the pipeline..."
-          # Add your pipeline execution command here
-          elif [ "$last_comment_body" == "deny" ]; then
-          echo "Pipeline denied. Failing the pipeline."
-          exit 1
+          
+          if [[ "$last_comment_body" =~ ^approve$ ]]; then
+            echo "Pipeline approved. Running the pipeline..."
+            # Add your pipeline execution command here
+          elif [[ "$last_comment_body" == "deny" ]]; then
+            echo "Pipeline denied. Failing the pipeline."
+            exit 1
           else
-          echo "No action required for this comment."
-          exit 0
+            echo "No action required for this comment."
+            exit 0
           fi
-          if: contains(github.event.comment.body, 'approve') && github.event.comment.body == 'approve'
+
 
       # - name: Run Pipeline
       #   if: success()  # Only run if the comment was processed successfully
