Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,12 +1,12 @@
 name: Issue approval Test
 
-# on:
-#   issues:
-#     types:
-#       - closed
-  # issue_comment:
-  #   types:
-  #     - created
+on:
+  issues:
+    types:
+      - closed
+  issue_comment:
+    types:
+      - created
 
 jobs:
   run_pipeline:
@@ -26,12 +26,15 @@ jobs:
         run: |
           comment_body=$(jq -r .comment.body "${{ github.event_path }}")
           echo "Comment Body: $comment_body"
-  
-          if [[ "$comment_body" =~ \bcool\b ]]; then
-            echo "Cool! Proceeding with the pipeline..."
+
+          if [[ "$comment_body" =~ \bapprove\b ]]; then
+            echo "Pipeline approved. Running the pipeline..."
             # Add your pipeline execution command here
+          elif [[ "$comment_body" =~ \bdeny\b ]]; then
+            echo "Pipeline denied. Failing the pipeline."
+            exit 1
           else
-            echo "No action required for this comment or not using the approved keyword. Exiting..."
+            echo "No action required for this comment."
             exit 0
           fi
 
@@ -44,7 +47,7 @@ jobs:
                          jq '.[] | select(.state == "APPROVED")' | \
                          jq length)
 
-          required_approvals=1  # Set the number of required approvals
+          required_approvals=2  # Set the number of required approvals
 
           if [ "$approvals" -ge "$required_approvals" ]; then
             echo "Required approvals met. Running the pipeline..."
@@ -60,7 +63,7 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 14
+         node-version: 14
 
       - name: Install dependencies
         run: npm install
