Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,12 +3,13 @@ name: test Pipeline
 on:
   issues:
     types:
-      - closed
+      - closed    
+     
 
 jobs:
   run_pipeline:
     runs-on: ubuntu-latest
-
+ 
     steps:
       - name: Check if the comment is on a closed issue
         env:
@@ -27,33 +28,30 @@ jobs:
           fi
 
       - name: Check comment for approval or denial
-        id: check_approval
         run: |
           comments_url=$(jq -r '.issue.comments_url' "${{ github.event_path }}")
           last_comment_body=$(curl -s "${comments_url}" | jq -r '.[-1].body')
           echo "Last Comment Body: $last_comment_body"
-
+          
+        
           if [[ "$last_comment_body" == *"approve"* ]]; then
-            echo "Pipeline approved. Setting approval status to true..."
-            echo "::set-output name=approval::true"
+            echo "Pipeline approved. Running the pipeline..."
+            # Add your pipeline execution command here
           elif [[ "$last_comment_body" == *"deny"* ]]; then
-            echo "Pipeline denied. Setting approval status to false."
-            echo "::set-output name=approval::false"
+            echo "Pipeline denied. Failing the pipeline."
+            exit 1
           else
-            echo "No action required for this comment. Setting approval status to false."
-            echo "::set-output name=approval::false"
+            echo "No action required for this comment."
+            exit 0
           fi
-
       # - name: Run Pipeline
-      #   if: success() && steps.check_approval.outputs.approval == 'true' # Only run if the comment was processed successfully and approval was received
+      #   if: success()  # Only run if the comment was processed successfully
       #   run: |
       #     # Your pipeline steps go here
-      #     ./run_pipeline.sh
-
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: 14
+         node-version: 14 
